spring:
  datasource:
    url: ${PAIRAGON_DATASOURCE_URL:jdbc:postgresql://localhost:5432/standup}
    username: ${PAIRAGON_DATASOURCE_USERNAME:standup}
    password: ${PAIRAGON_DATASOURCE_PASSWORD:standup}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  port: 8080

logging:
  level:
    com.standup: DEBUG
